### ISSUE TITLE
Follow up - TV not adding

### ISSUE THREAD

**Issue by alexescarce** [o-lukas/homebridge-smartthings-tv#321] opened 2024-03-17 07:00 UTC
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

Sorry, delete if necessary, i am new to github and do not know how to reopen an issue. But i get the following even after unpairing the tv from my homebridge:

[Living Room TV] Capability Media Input Source might not work as expected because it's status is: proposed

The tv is literally just on one of the hdmi inputs

### Environment Information

```markdown
- Plugin Version:
- Homebridge Version: <!-- homebridge -V -->
- Node.js version: <!-- node -v -->
- NPM version: <!-- npm -v -->
- Operating System: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
```

**Comment by o-lukas** [comment] 2024-03-20 06:40
Duplicate of #314

**Closed** 2024-03-20 06:39 UTC
Labels: question
