### ISSUE TITLE
The TV does not turn on

### ISSUE THREAD

**Issue by LavlavOP** [o-lukas/homebridge-smartthings-tv#3] opened 2023-02-14 07:56 UTC
You can turn off the TV but you can't turn it on

**Comment by o-lukas** [comment] 2023-02-14 08:07
Have you set the mac address of your TV in the config? Otherwise wol will not work and turning the TV on using the SmartThings API is pretty buggy...

**Comment by rooskie94** [comment] 2023-03-06 18:13
Had the same issue, fixed it by removing the device ID in device mappings and leaving it blank and applying/restarting home bridge. Hopefully this helps you.

**Comment by o-lukas** [comment] 2023-03-08 17:34
I'm closing this issue for now as it seems to work now. 

If the problem does still exist please open a new issue and use the issue template to provide some more information as I'm not able to reproduce the problem.

**Closed by o-lukas** 2023-03-08 17:34 UTC
Labels: bug
